plugin:
  name: Batch IFC & DWG Export
  UUID: 7612a6aa-0e83-4b62-a548-d18a3c30e7d7
  version: 0.1.5
  developer: allplan-gmbh
  default-language: en
  min-allplan-version: 2026

installation:
  target-location: STD